### ISSUE TITLE
Can't get working with just an email field input?

### ISSUE THREAD

**Issue by j-greig** [clearbold/craft-campaignmonitor-lists#1]
Hi there and thanks for this plugin.

What are the minimum required fields to make this plugin work?

If the form contains just an email field, I get errors like

`Invalid argument supplied for foreach()
1. in /Users/jamesgreig/Repos/todd-duncan/vendor/clearbold/craft-campaignmonitor-lists/src/controllers/SubscribeController.php at line 41`

Thanks!

**Comment by heymarkreeves** [comment]
Hello!

Could you paste in your form code? That error indicates it's not even getting the fields you're submitting.

**Comment by j-greig** [comment]
```
<form method="post" action="" accept-charset="UTF-8">
      {{ csrfInput() }}
      <input type="hidden" name="action" value="cm-lists/subscribe" />
      <input type="hidden" name="redirect" value="{{ ''|hash }}" />
      <input type="hidden" name="listId" value="{{ 'heeeeeeyyyyyyyyyyy'|hash }}" />

      <p class="tracked white tc">{{ newsletter.newsletterSignupCall }}</p>
      <div class="email flex br1 justify-center mb3 mb0-ns">
        <input class="input-reset bg-white w5 pa3 bn" type="email" name="email" placeholder="Enter your email">
        <input class="grey pa3 bn" type="submit" value="Send" />
      </div>
</form>`

**Comment by j-greig** [comment]
(Thanks for checking this!)

**Comment by heymarkreeves** [comment]
Thanks! v1.1.2 is up with a fix for that.

I had a custom field in my test, so I assumed I would be getting the values inside a fields loop, but wasn't using `fields[]` syntax for the main fields (email, firstname, lastname, *or* fullname).

You should now be able to submit with just email, or just email + name fields.

Let me know if that works?

**Comment by heymarkreeves** [comment]
@j-greig Is this working for you now? All set?
