### ISSUE TITLE
"Please provide a consent to track value." response when subscribing via XMLHttpRequest

### ISSUE THREAD

**Issue by jpcarpenter** [clearbold/craft-campaignmonitor-lists#11]
While attempting to submit a subscribe form via XMLHttpRequest, the response returns a 404 with the following message: 

```
reason: "Please provide a consent to track value."
statusCode: 400
success: false
```

I investigated within the CM API docs, and found that by adding a `ConsentToTrack` option to the subscriber list service, the response returns successfully. Below is where I added the option:

```
 $subscriber = array(
   'EmailAddress' => $email,
   'Name' => $fullName,
   'CustomFields' => $additionalFields,
   'Resubscribe' => true,
   "ConsentToTrack" => "Unchanged"
);
```

Once added, the subscribe functionality works as expected.

**Comment by heymarkreeves** [comment]
This has been addressed in #10, which updated the create-send library to resolve PHP's deprecated use of curly braces.
