### ISSUE TITLE
Allow CAPTCHA or honeypot field

### ISSUE THREAD

**Issue by wallacio** [clearbold/craft-campaignmonitor-lists#12]
A form I've created which uses this plugin for subscriptions is being hammered by a spam bot. Is it possible to add a honeypot field, or a CAPTCHA to the form?

This may be possible with an event handler, so if you can point me in the right direction I'd be grateful.

**Comment by heymarkreeves** [comment]
Hi, @wallacio!

If I provided a field name for a honeypot field, I can just check in the controller if that field was submitted and has a value and skip pushing the subscriber to Campaign Monitor if it does? It'd fail silently, so it'd redirect or respond normally. Would that suffice?

**Comment by wallacio** [comment]
Oh wow, you're on the ball!!

I think in practice, that would work fine and is comparable to how other things that implement a honeypot work. For maximum happiness, it would be nice if:
a) If silently failing, the honey monsters were at least logged (it's unclear what my thinking behind that is, if I'm honest)
b) the honeypot field name was configurable

**Comment by heymarkreeves** [comment]
Let's start with something simple, as this plugin doesn't have any configurable values and specifying the name of the honeypot field would just be another hidden form field passing that through. I made the field name something that would obfuscate its intent.

If you add this to your subscribe form:

```
<input type="hidden" name="field-7726" value="" />
```

That's your honeypot field.

If a value is submitted for that field, I'm skipping the push to Campaign Monitor and writing an info-level entry to your Craft `storage/logs/web.log`. You can find spam submissions by searching for the 🚫 emoji in that file.

I've pushed this up without tagging a new version. You can just swap in the updated [subscribe controller](https://github.com/clearbold/craft-campaignmonitor-lists/blob/master/src/controllers/SubscribeController.php) to test it if you'd like. Let me know how that works?

**Comment by wallacio** [comment]
This is excellent, thank you. I'll push that up to production this evening and see how it goes.

I appreciate the additional complexity in exposing settings to the user. I understood that spambots were smarter, looking specifically for fields with names such as "email" or "name" (whether that's true or not, I don't know) so if provision could be made to name a field accordingly, without clobbering any existing fields, then that would address that.

Very much appreciate how quickly you've jumped on this though - gold star from me.

**Comment by heymarkreeves** [comment]
I added a second case to the controller to check for a field named `email-7726`. You can try that in your template, too, and see if the generic `field-7726` or `email-7726` works better.

I'm inclined to think that if a bot is looking for a field named email it could also check to see if a field is hidden and skip that, too.

And I think CAPTCHAs are bad for UX :)

**Comment by wallacio** [comment]
Agreed on both of those sentiments. Thanks so much for pushing this up.
W.

**Comment by wallacio** [comment]
Ok - this kinda works. Small bugfix required, to make sure there's a $response if not calling the CM subscribe service, e.g.

```
        if (!$honeypot) {
            $response = CmLists::getInstance()->cmListService->subscribe($listId, $email, $fullName, $additionalFields);
        }
        else {
            Craft::info("Campaign Monitor spam blocked: $email", __METHOD__);
            $response = [
                "success" => true, 
                "statusCode" => 200
            ];
        }
        return $request->getBodyParam('redirect') ? $this->redirectToPostedUrl() : $this->asJson($response);
```

No log entry though, but I think that's more to do with info not being logged in 'live' mode

**Comment by wallacio** [comment]
@heymarkreeves - could you possibly create a new release with this honeypot field plus the fix above in, ignoring the bit about logging? It's a minor edit to the if/else for the honeypot.
Cheers!

**Comment by heymarkreeves** [comment]
@wallacio Would you mind forking the codebase and sending this back as a pull request? Then I can pull that in and tag a new release. Thanks!

**Comment by wallacio** [comment]
@heymarkreeves - I made a PR, would you mind checking this and merging for release if you're happy with it? Cheers!

**Comment by heymarkreeves** [comment]
@wallacio Sorry about that. Should be all set!
