### ISSUE TITLE
Craft4 version?

### ISSUE THREAD

**Issue by timbertens** [clearbold/craft-campaignmonitor-lists#14]
Are you considering a Craft 4 compatible version of this plugin ?

**Comment by heymarkreeves** [comment]
Hi, @timbertens! Thanks for reaching out. 287 installs prior to this month isn't a bad number for a plugin's popularity, but it's not something I'm actively using and I don't have a sense of the CM userbase that I once did, with the number of competitors now for marketing automation or transactional email.

Thus I'm hard-pressed to put time against Craft 4 support.

I'm assuming the decline in installs I see on the plugin's page is the result of Craft 4 migrations that have uninstalled it.

I'm happy to review and approve pull requests if anyone would like to tackle it. The underlying CM Service plugin probably needs attention as well.
