### ISSUE TITLE
Subscribe form dumps form data and exits rather than submitting.

### ISSUE THREAD

**Issue by bendesilva** [clearbold/craft-campaignmonitor-lists#2]
Hi,

Thanks for the work on this!

Just trying out the plugin and noticed the subscribe form wasn't working and the request would just dump the input data. Noticed the below line in the subscribe controller.

https://github.com/clearbold/craft-campaignmonitor-lists/blob/6caea345a652758556506a4ede78517a4c34df6c/src/controllers/SubscribeController.php#L70

In addition I noticed the "redirect" param is required, but later on is used as a conditional to check whether to redirect or return the result of the submission as JSON. Would be really useful to have that as an option...

**Comment by heymarkreeves** [comment]
Thanks for the feedback and for spotting that dump! Both issues are fixed in v1.1.3. Please confirm and close.

**Comment by bendesilva** [comment]
Perfect, thanks!
