### ISSUE TITLE
Missing redirect parameter causing error in >=1.1.5?

### ISSUE THREAD

**Issue by brettgullan** [clearbold/craft-campaignmonitor-lists#3]
Hello!

I think I've encountered a bug with v1.1.5 …

I'm submitting a form to `cm-lists/subscribe` via ajax, and after upgrading to v1.1.5 am now getting a request error on submission.

It looks like the call from `SubscribeController` to `ListService` passes the `$redirect` argument as null, which fails the static typing on the ListService function? But `$redirect` isn't used in the ListService function? So maybe not required?

Would be great to get a patch for this.

Thanks,

Brett

**Comment by brettgullan** [comment]
Added a PR in case that helps.

**Comment by heymarkreeves** [comment]
Fixed via PR.
