### ISSUE TITLE
Main plugin page failing on Craft 3.2

### ISSUE THREAD

**Issue by alexhillel** [clearbold/craft-campaignmonitor-lists#5]
Just installed the version 1.1.7 plugin from the store on Craft 3.2.9, and navigating to the Campaign Monitor Lists sidebar link results in a error screen with message "Call to a member function getSettings() on null", referring the file 'craft-campaignmonitor-service/src/services/CampaignMonitorService.php', line 41.

**Comment by heymarkreeves** [comment]
Hi, Alex! Just checking the obvious – Have you supplied your API credentials via the Campaign Monitor Service plugin?

**Comment by alexhillel** [comment]
Sorry! Installing from the plugin store installed the Lists plugin, but didn't automatically install the Service plugin. My mistake!

**Comment by heymarkreeves** [comment]
Glad you're all set, and I'll take a look at that. It's been a while since I worked on it, but I feel like that should've been installed as a dependency. Or are you saying the Service plugin was in place, but you needed to flip its status to installed in the control panel?

**Comment by alexhillel** [comment]
Yes, it had installed but needed manually enabling in the settings page. All good now, looks like a really useful plugin, thank you!

**Comment by heymarkreeves** [comment]
Awesome. Thanks for the follow-up. Let me know if there's anything else you might find helpful that I can put in a feature backlog.
